apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-19T06:41:42Z"
  name: red-app
  namespace: default
  resourceVersion: "1037"
  uid: ee80cbf7-400a-4e90-a2fa-b239184c2be5
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8bb4v
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sleep
    - "20"
    image: busybox
    imagePullPolicy: Always
    name: init-myservice
  nodeName: controlplane