apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
    - name: nginx-bee-container
      image: nginx
  tolerations:
    - key: spray
      operator: "Equal"
      value: mortein
      effect: NoSchedule