apiVersion: v1
kind: Pod
metadata:
  name: elephant
  labels:
    app: elephant-app
spec:
  containers:
    - name: elephant-container
      image: polinux/stress
      resources:
        limits:  
          memory: 20Mi # Extend limit to 20Mi where the process requires 15Mi
        requests:
          memory: 15Mi