apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2024-07-17T13:59:32Z"
  generation: 4
  name: frontend
  namespace: default
  resourceVersion: "1262"
  uid: 654cd95d-daa4-4c1f-a4d7-d1e3788ae38a
spec:
  minReadySeconds: 20
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: webapp
      #rollingUpdate:
      # The default value is 25%.
      # maxUnavailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process.
      #maxUnavailable: 20% # The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%). 
      # maxSurge is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
      #maxSurge: 20% 
  strategy:         #Or strategy:
    type: Recreate    # type: RollingUpdate
                      # maxSurge:75%
                     # maxUnavailable: Specifies the maximum number or percentage of pods that can be unavailable during the update. Default is 25%. This means that during the update, at least 75% of the desired number of pods must be available.
                     #maxSurge: Specifies the maximum number or percentage of pods that can be created above the desired number of pods. Default is 25%. This means that during the update, there can be at most 125% of the desired number of pods
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: webapp
    spec:
      containers:
      - image: kodekloud/webapp-color:v3
        imagePullPolicy: IfNotPresent
        name: simple-webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2024-07-17T14:10:41Z"
    lastUpdateTime: "2024-07-17T14:10:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-17T13:59:32Z"
    lastUpdateTime: "2024-07-17T14:10:41Z"
    message: ReplicaSet "frontend-7f9fcb55d7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4